export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const UPDATE_USER = 'UPDATE_USER'